name: fulton-recovery
version: 1.0-SNAPSHOT
author: viviridian
main: space.vvn.Main
api-version: 1.14
commands:
  fulton:
    description: fulton recovery system
  fulton_home:
    description: set home for fulton recovery system